apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitops-ns-prd
nameSuffix: -prd
resources:
- ../../base/app
- namespace.yml
replicas:
- count: 3
  name: info-server
configMapGenerator:
- name: nginx-conf-kustom
  files:
  - html/index.html
  - html/main.css
